# Generated by Django 6.0.2 on 2026-02-24 15:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('risk_score', models.IntegerField()),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=8)),
                ('triggered_rules', models.JSONField()),
                ('assessed_at', models.DateTimeField(auto_now_add=True)),
                ('assessed_by', models.CharField(default='system', max_length=64)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessment', to='transactions.transaction')),
            ],
        ),
    ]
