# Generated by Django 6.0.2 on 2026-02-24 14:33

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tx_hash', models.CharField(max_length=128)),
                ('blockchain', models.CharField(max_length=32)),
                ('from_address', models.CharField(max_length=256)),
                ('to_address', models.CharField(max_length=256)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('asset', models.CharField(max_length=16)),
                ('block_number', models.BigIntegerField(blank=True, null=True)),
                ('tx_timestamp', models.DateTimeField()),
                ('ingestion_source', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('VALIDATED', 'Validated'), ('SCORED', 'Scored'), ('FLAGGED', 'Flagged')], default='RECEIVED', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['tx_hash'], name='transaction_tx_hash_2e17d1_idx'), models.Index(fields=['from_address'], name='transaction_from_ad_6dbcc9_idx'), models.Index(fields=['to_address'], name='transaction_to_addr_b82a15_idx'), models.Index(fields=['status'], name='transaction_status_71abbb_idx')],
                'constraints': [models.UniqueConstraint(fields=('tx_hash', 'blockchain'), name='unique_tx_per_blockchain')],
            },
        ),
    ]
